apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payrollflow-keyvault
  namespace: payrollflow
spec:
  provider: azure

  secretObjects:
    - secretName: payrollflow-secrets
      type: Opaque
      data:
        - objectName: JWT-SECRET
          key: JWT_SECRET
        - objectName: AZURE-GRAPH-CLIENT-ID
          key: AZURE_GRAPH_CLIENT_ID
        - objectName: AZURE-GRAPH-CLIENT-SECRET
          key: AZURE_GRAPH_CLIENT_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e49c8e7d-0921-47f8-a6c0-d3631bb5e59b"
    keyvaultName: "kv-payrollflow-yao"
    tenantId: "c8bb705c-2d97-4d0b-b692-37cc14ae4d29"

    objects: |
      array:
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: AZURE-GRAPH-CLIENT-ID
          objectType: secret
        - |
          objectName: AZURE-GRAPH-CLIENT-SECRET
          objectType: secret
