apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: payrollflow-azurefile
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  skuName: Standard_LRS
  protocol: smb
mountOptions:
  - dir_mode=0770
  - file_mode=0660
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
  - nosharesock
  - actimeo=30
