apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payroll-data
  namespace: payrollflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: payrollflow-azurefile
  resources:
    requests:
      storage: 5Gi
